development:
  adapter:  mysql2
  # encoding:  utf8
  reconnect: false
  database:  lamule
  pool: 5
  socket: /Applications/MAMP/tmp/mysql/mysql.sock

production:
  adapter: postgresql
  encoding: utf8
  database: 
  username: 
  password: 
  host: ec2-54-197.compute-1.amazonaws.com